import React, { useState, useEffect, useCallback } from 'react';
import { 
  Activity, 
  History as HistoryIcon, 
  Settings as SettingsIcon, 
  Play, 
  Zap, 
  LayoutDashboard,
  Box,
  Moon,
  Sun,
  Menu,
  X,
  Plus
} from 'lucide-react';
import { AppView, ApiRequest, ApiResponse, HistoryItem, SettingsState, AISuggestion } from './types';
import { analyzeApiTransaction } from './services/geminiService';

// --- Components ---
import HomeScreen from './components/HomeScreen';
import RequestScreen from './components/RequestScreen';
import ProcessingScreen from './components/ProcessingScreen';
import ResultScreen from './components/ResultScreen';
import AISuggestionScreen from './components/AISuggestionScreen';
import HistoryScreen from './components/HistoryScreen';
import SettingsScreen from './components/SettingsScreen';

const DEFAULT_SETTINGS: SettingsState = {
  theme: 'dark', // Matching the provided images
  geminiApiKey: '',
  defaultMethod: 'GET',
  defaultTimeout: 5000,
  autoScroll: true,
  autoGenerateDocs: true,
  saveHistory: true,
  compactMode: false,
};

const App: React.FC = () => {
  // --- State ---
  const [currentView, setCurrentView] = useState<AppView>(AppView.HOME);
  const [settings, setSettings] = useState<SettingsState>(() => {
    const saved = localStorage.getItem('api_doctor_settings');
    return saved ? JSON.parse(saved) : DEFAULT_SETTINGS;
  });
  const [history, setHistory] = useState<HistoryItem[]>(() => {
    const saved = localStorage.getItem('api_doctor_history');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [activeRequest, setActiveRequest] = useState<ApiRequest>({
    id: '',
    url: 'https://jsonplaceholder.typicode.com/todos/1',
    method: 'GET',
    headers: [],
    params: [],
    body: '',
    timestamp: 0,
  });

  const [lastResponse, setLastResponse] = useState<ApiResponse | null>(null);
  const [aiAnalysis, setAiAnalysis] = useState<AISuggestion | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // --- Effects ---
  useEffect(() => {
    localStorage.setItem('api_doctor_settings', JSON.stringify(settings));
    if (settings.theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [settings]);

  useEffect(() => {
    if (settings.saveHistory) {
      localStorage.setItem('api_doctor_history', JSON.stringify(history));
    }
  }, [history, settings.saveHistory]);

  // --- Actions ---
  const handleStartRequest = async (req: ApiRequest) => {
    setActiveRequest(req);
    setCurrentView(AppView.PROCESSING);
    setIsProcessing(true);
    setLastResponse(null);
    setAiAnalysis(null);

    const startTime = performance.now();
    
    try {
      // Prepare URL with params
      const urlObj = new URL(req.url);
      req.params.forEach(p => {
        if(p.key) urlObj.searchParams.append(p.key, p.value);
      });

      const headers: Record<string, string> = {};
      req.headers.forEach(h => {
        if(h.key) headers[h.key] = h.value;
      });

      const options: RequestInit = {
        method: req.method,
        headers: headers,
      };

      if (req.method !== 'GET' && req.method !== 'HEAD' && req.body) {
        options.body = req.body;
      }

      const res = await fetch(urlObj.toString(), options);
      const endTime = performance.now();
      
      const size = res.headers.get('content-length') ? parseInt(res.headers.get('content-length')!) : 0;
      const responseData = await res.json().catch(() => ({ message: "Non-JSON response" })); // simplified text handling

      const apiResponse: ApiResponse = {
        statusCode: res.status,
        statusText: res.statusText,
        headers: Object.fromEntries(res.headers.entries()),
        data: responseData,
        size: size || JSON.stringify(responseData).length,
        time: Math.round(endTime - startTime),
      };

      setLastResponse(apiResponse);
      
      // Save to history
      const newHistoryItem: HistoryItem = {
        request: req,
        response: apiResponse,
        timestamp: Date.now(),
      };
      setHistory(prev => [newHistoryItem, ...prev]);

      // Move to results after short delay for visual effect
      setTimeout(() => {
        setIsProcessing(false);
        setCurrentView(AppView.RESULTS);
        
        // Auto trigger AI if key exists
        if (settings.geminiApiKey && settings.autoGenerateDocs) {
          triggerAiAnalysis(req, apiResponse);
        }
      }, 1500);

    } catch (error: any) {
      const endTime = performance.now();
      const errorResponse: ApiResponse = {
        statusCode: 0,
        statusText: "Network Error",
        headers: {},
        data: { error: error.message, hint: "Check CORS or URL validity" },
        size: 0,
        time: Math.round(endTime - startTime),
        error: error.message
      };
      setLastResponse(errorResponse);
      setIsProcessing(false);
      setCurrentView(AppView.RESULTS);
      
       // Save failed history
       const newHistoryItem: HistoryItem = {
        request: req,
        response: errorResponse,
        timestamp: Date.now(),
      };
      setHistory(prev => [newHistoryItem, ...prev]);
    }
  };

  const triggerAiAnalysis = async (req: ApiRequest, res: ApiResponse) => {
    if (!settings.geminiApiKey) return;
    try {
      const suggestion = await analyzeApiTransaction(req, res, settings.geminiApiKey);
      setAiAnalysis(suggestion);
    } catch (e) {
      console.error(e);
    }
  };

  const clearHistory = () => {
      setHistory([]);
      localStorage.removeItem('api_doctor_history');
  }

  // --- Rendering ---
  const renderView = () => {
    switch (currentView) {
      case AppView.HOME:
        return <HomeScreen onStart={() => setCurrentView(AppView.REQUEST)} />;
      case AppView.REQUEST:
        return <RequestScreen 
          initialRequest={activeRequest} 
          onSubmit={handleStartRequest} 
          defaultMethod={settings.defaultMethod}
        />;
      case AppView.PROCESSING:
        return <ProcessingScreen />;
      case AppView.RESULTS:
        return <ResultScreen 
          response={lastResponse} 
          request={activeRequest} 
          onAnalyze={() => {
            setCurrentView(AppView.AI_SUGGESTIONS);
            if (!aiAnalysis && settings.geminiApiKey && lastResponse) {
               triggerAiAnalysis(activeRequest, lastResponse);
            }
          }}
          onRetry={() => handleStartRequest(activeRequest)}
        />;
      case AppView.AI_SUGGESTIONS:
        return <AISuggestionScreen 
          suggestion={aiAnalysis} 
          isLoading={!aiAnalysis} 
          hasKey={!!settings.geminiApiKey}
        />;
      case AppView.HISTORY:
        return <HistoryScreen 
          history={history} 
          onSelect={(item) => {
            setActiveRequest(item.request);
            setLastResponse(item.response);
            setCurrentView(AppView.RESULTS);
          }} 
          onDelete={() => clearHistory()}
        />;
      case AppView.SETTINGS:
        return <SettingsScreen 
          settings={settings} 
          onSave={setSettings} 
          onClearHistory={clearHistory}
        />;
      default:
        return <HomeScreen onStart={() => setCurrentView(AppView.REQUEST)} />;
    }
  };

  const NavItem = ({ view, icon: Icon, label }: { view: AppView, icon: any, label: string }) => (
    <button
      onClick={() => {
        setCurrentView(view);
        setIsSidebarOpen(false);
      }}
      className={`flex items-center space-x-3 w-full px-4 py-3 rounded-xl transition-all duration-200 ${
        currentView === view 
          ? 'bg-primary/10 text-primary font-medium shadow-sm' 
          : 'text-gray-500 hover:bg-gray-100 dark:hover:bg-slate-800 dark:text-gray-400'
      }`}
    >
      <Icon size={20} />
      <span>{label}</span>
    </button>
  );

  return (
    <div className="flex h-screen bg-gray-50 dark:bg-[#0b1120] text-slate-900 dark:text-white overflow-hidden font-sans">
      {/* Mobile Sidebar Overlay */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={() => setIsSidebarOpen(false)}
        />
      )}

      {/* Sidebar Navigation */}
      <aside className={`
        fixed lg:static inset-y-0 left-0 z-50 w-64 bg-white dark:bg-[#111827] border-r border-gray-200 dark:border-gray-800 
        transform transition-transform duration-300 ease-in-out lg:transform-none
        ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="flex flex-col h-full">
          <div className="p-6 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Box className="text-primary" size={28} />
              <span className="text-xl font-bold tracking-tight">API Doctor</span>
            </div>
            <button onClick={() => setIsSidebarOpen(false)} className="lg:hidden">
              <X size={24} />
            </button>
          </div>

          <nav className="flex-1 px-4 space-y-2 overflow-y-auto py-4">
            <NavItem view={AppView.HOME} icon={LayoutDashboard} label="Home" />
            <NavItem view={AppView.REQUEST} icon={Plus} label="New Request" />
            <NavItem view={AppView.RESULTS} icon={Activity} label="Results" />
            <NavItem view={AppView.AI_SUGGESTIONS} icon={Zap} label="AI Suggestions" />
            <NavItem view={AppView.HISTORY} icon={HistoryIcon} label="History" />
            <div className="pt-4 mt-4 border-t border-gray-100 dark:border-gray-800">
              <NavItem view={AppView.SETTINGS} icon={SettingsIcon} label="Settings" />
            </div>
          </nav>

          <div className="p-4 border-t border-gray-100 dark:border-gray-800">
             <div className="flex items-center justify-between px-4 py-2 bg-gray-50 dark:bg-slate-800 rounded-lg">
                <span className="text-xs font-medium text-gray-500 dark:text-gray-400">v1.2.0</span>
                <div className="flex space-x-2">
                  {settings.theme === 'light' ? 
                    <Moon size={16} className="cursor-pointer text-gray-500" onClick={() => setSettings({...settings, theme: 'dark'})} /> :
                    <Sun size={16} className="cursor-pointer text-gray-400" onClick={() => setSettings({...settings, theme: 'light'})} />
                  }
                </div>
             </div>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col h-full relative overflow-hidden">
        {/* Mobile Header */}
        <header className="lg:hidden flex items-center justify-between p-4 bg-white dark:bg-[#111827] border-b border-gray-200 dark:border-gray-800">
          <button onClick={() => setIsSidebarOpen(true)}>
            <Menu size={24} />
          </button>
          <span className="font-semibold">API Doctor</span>
          <div className="w-6" /> {/* Spacer */}
        </header>

        {/* View Content */}
        <div className="flex-1 overflow-auto p-4 md:p-8 scroll-smooth">
          <div className="max-w-4xl mx-auto h-full">
            {renderView()}
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;