export enum AppView {
  HOME = 'HOME',
  REQUEST = 'REQUEST',
  PROCESSING = 'PROCESSING',
  RESULTS = 'RESULTS',
  AI_SUGGESTIONS = 'AI_SUGGESTIONS',
  HISTORY = 'HISTORY',
  SETTINGS = 'SETTINGS',
}

export interface ApiRequest {
  id: string;
  url: string;
  method: string;
  headers: { key: string; value: string }[];
  params: { key: string; value: string }[];
  body: string;
  timestamp: number;
}

export interface ApiResponse {
  statusCode: number;
  statusText: string;
  headers: Record<string, string>;
  data: any;
  size: number;
  time: number; // milliseconds
  error?: string;
}

export interface HistoryItem {
  request: ApiRequest;
  response: ApiResponse | null;
  timestamp: number;
}

export interface SettingsState {
  theme: 'light' | 'dark';
  geminiApiKey: string;
  defaultMethod: string;
  defaultTimeout: number;
  autoScroll: boolean;
  autoGenerateDocs: boolean;
  saveHistory: boolean;
  compactMode: boolean;
}

export interface AISuggestion {
  documentation: string;
  improvements: string[];
  security: string[];
  schemaUpdates: string;
  codeSnippet: string;
}